export const FEATURE_FLAGS = {
  BLOG_ENABLED: false,
  RESOURCES_ENABLED: false,
  TESTIMONIALS_ENABLED: false,
  STARTING_POINT_QUIZ_ENABLED: true,
  DELIVERABLES_GALLERY_ENABLED: true,
  INDUSTRY_MODULES_ENABLED: true
} as const;
